### ISSUE TITLE
Composer package not found

### ISSUE THREAD

**Issue by odan** [slimphp/Slim-Console#46]
When I run `composer require slim/console:^0.1` I get the following error:

```
[InvalidArgumentException]                                                                                                                        
Could not find a matching version of package slim/console. 
Check the package spelling, your version constraint and that the package is available  
in a stability which matches your minimum-stability (stable).      
```

I also tried to add `"minimum-stability": "dev",` to my composer.json file.

It looks like the package does not exist on packagist: https://packagist.org/search/?q=slim/console

> No packages found.

**Comment by ABGEO** [comment]
Hello @odan,

The Slim Console not yet published on Packagist.

**Comment by odan** [comment]
Ok

**Comment by l0gicgate** [comment]
@odan just pushed a release:
https://github.com/slimphp/Slim-Console/releases/tag/0.1

Also available on packagist:
https://packagist.org/packages/slim/console
