### ISSUE TITLE
Configuration Object

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim-Console#6]
We are going to need to create a global configuration object to keep track of paths and other settings.

**It will need to keep track of these items:**
- Source path (default: src)
- External commands path (default: Application/Commands as established in #3)
- Public index path (default: public/index.php)
- Bootstrap directory (default: app)
_Not sure if we do need all of these, I'm just brainstorming)_

**We should enable populating that object using:**
- JSON Configuration
- YAML Configuration
- PHP Configuration
- Env Variables (These will always take precedence over all others)

What should the configuration files be named?
- slim.config.(json|yaml|php)?

**Comment by zhorton34** [comment]
`slim-console.config.php`?

I would highly recommend creating it as a `.php` file.

Any other format will require that we parse it and format it over to `php` so we can use the configuration to preset/make stuff.

**Comment by flangofas** [comment]
@l0gicgate I can work on this one if it is OK 😄

**Comment by l0gicgate** [comment]
Let’s proceed with the initial configuration being `.php` and further down the road we can offer other options if requested!

And @flangofas absolutely!

**Comment by flangofas** [comment]
@l0gicgate For now, should I use the following parameters within the Config Object?
```php
    protected static $defaultParams = [
        'root'          => 'Absolute path of the project\'s root directory',
        'bootstrap'     => 'app',
        'commandsDir'   => 'Application/Commands',
        'public'        => 'public/index.php',
        'src'           => 'src',
    ];
```

**Comment by l0gicgate** [comment]
I think we should probably keep the naming uniform and alphabetized keys:
```php
    $defaultParams = [
        'bootstrapDir'	=> 'app',
        'commandsDir'	=> 'Application/Commands',
        'indexDir'	=> 'public',
        'indexFile'	=> 'index.php',
        'rootDir'	=> 'Absolute path of the project\'s root directory',
        'sourceDir'	=> 'src',
    ];
```

I'm not final on this but that's what I'm thinking. Thoughts @ABGEO07?

**Comment by flangofas** [comment]
@l0gicgate @ABGEO07 
Agreed. 👍 
And the environment variables would be these:
```
SLIM_CONSOLE_BOOTSTRAP_DIR
SLIM_CONSOLE_COMMANDS_DIR
SLIM_CONSOLE_INDEX_DIR
SLIM_CONSOLE_INDEX_FILE
SLIM_CONSOLE_SOURCE_DIR
```

**Comment by ABGEO** [comment]
> ```
> $defaultParams = [
>         'bootstrapDir'	=> 'app',
>         'commandsDir'	=> 'Application/Commands',
>         'indexDir'	=> 'public',
>         'indexFile'	=> 'index.php',
>         'rootDir'	=> 'Absolute path of the project\'s root directory',
>         'sourceDir'	=> 'src',
>     ];
> ```

@l0gicgate this is a good structure :+1: But i have one offer for improvement:
What do you think about using some kind of placeholders like
```php
...
'commandsDir' => '{sourceDir}/Commands', // or %sourceDir%
'sourceDir'   => 'src',
...
```
or something else? This would be good practice when we need to reuse some parameters in other parameters.

It will be easy to parse them using regex and replace before defining constants (or env variables).

**Comment by l0gicgate** [comment]
> What do you think about using some kind of placeholders like

I’m not so sure we need to go that complex. We should have path formatting done via internal functions. `sourceDir` is implied that it would prefix the `commandsDir` in this case.

We’ll have to see what @flangofas comes up with and we can make further decision once we see the initial config object.
